spring.application.name=taskManager

spring.datasource.url=jdbc:postgresql://localhost:5433/taskManagerbd
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

jwt.secret=my-super-secret-key
jwt.expiration=86400000